
version: "3"
services:
    server:
        container_name: server
        build: .
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        links:
            - mongo

    mongo:
        container_name: mongo
        image: mongo
        restart: always
        volumes:
            - ./server/storage:/data/db
        ports:
            - "27017:27017"
